	create table GALPAO (
        ID bigint generated by default as identity,
        NOME_GALPAO varchar(255),
        primary key (id)
    );
    
    create table ANDAR (
        ID bigint generated by default as identity,
        NUMERO_ANDAR bigint,
        GALPAO_ID bigint not null,
        primary key (id)
    );
    
    create table PATIO (
        ID bigint generated by default as identity,
        NUMERO_PATIO bigint,
        ANDAR_ID bigint not null,
        primary key (id)
    );
    
    create table BLOCO (
        ID bigint generated by default as identity,
        LETRA_BLOCO varchar(255),
        PATIO_ID bigint not null,
        primary key (id)
    );
    
    create table VAGA (
        ID bigint generated by default as identity,
        NUMERO_VAGA bigint,
        BLOCO_ID bigint not null,
        primary key (id)
    );
    
    create table MOTO (
        ID bigint generated by default as identity,
        STATUS varchar(255),
        MODELO varchar(255),
        MARCA varchar(255),
        PLACA varchar(255),
        CHASSI varchar(255),
        VAGA_ID bigint not null,
        primary key (id)
    );
    
    create table USUARIO (
        ID bigint generated by default as identity,
        NOME varchar(255),
        SENHA varchar(255),
        USERNAME varchar(255),
        CARGO varchar(255),
        primary key (id)
    );

    create table CARGO (
        ID bigint generated by default as identity,
        NOME varchar(255),
        primary key (id)
    );
    
    create table USUARIO_CARGO (
        USUARIO_ID bigint not null,
        CARGO_ID bigint not null,
        primary key (USUARIO_ID, CARGO_ID)
    );