ALTER TABLE ANDAR
  ADD CONSTRAINT fk_andar_galpao_id__ref_galpao_id
  FOREIGN KEY (GALPAO_ID) REFERENCES GALPAO(ID);

ALTER TABLE PATIO
  ADD CONSTRAINT fk_patio_andar_id__ref_andar_id
  FOREIGN KEY (ANDAR_ID) REFERENCES ANDAR(ID);

ALTER TABLE BLOCO
  ADD CONSTRAINT fk_bloco_patio_id__ref_patio_id
  FOREIGN KEY (PATIO_ID) REFERENCES PATIO(ID);

ALTER TABLE VAGA
  ADD CONSTRAINT fk_vaga_bloco_id__ref_bloco_id
  FOREIGN KEY (BLOCO_ID) REFERENCES BLOCO(ID);

ALTER TABLE MOTO
  ADD CONSTRAINT fk_moto_vaga_id__ref_vaga_id
  FOREIGN KEY (VAGA_ID) REFERENCES VAGA(ID);

ALTER TABLE USUARIO_CARGO
  ADD CONSTRAINT fk_usuario_cargo_usuario_id__ref_usuario_id
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID);

ALTER TABLE USUARIO_CARGO
  ADD CONSTRAINT fk_usuario_cargo_cargo_id__ref_cargo_id
  FOREIGN KEY (CARGO_ID) REFERENCES CARGO(ID);
