INSERT INTO GALPAO(NOME_GALPAO) VALUES('Galpao Moema');
INSERT INTO GALPAO(NOME_GALPAO) VALUES('Galpao Santo Amaro');
INSERT INTO GALPAO(NOME_GALPAO) VALUES('Galpao Liberdade');
INSERT INTO GALPAO(NOME_GALPAO) VALUES('Galpao Berrini');
INSERT INTO GALPAO(NOME_GALPAO) VALUES('Galpao Pinheiros');

INSERT INTO ANDAR(NUMERO_ANDAR, GALPAO_ID) VALUES(1, 1);
INSERT INTO ANDAR(NUMERO_ANDAR, GALPAO_ID) VALUES(2, 1);
INSERT INTO ANDAR(NUMERO_ANDAR, GALPAO_ID) VALUES(1, 2);
INSERT INTO ANDAR(NUMERO_ANDAR, GALPAO_ID) VALUES(1, 3);
INSERT INTO ANDAR(NUMERO_ANDAR, GALPAO_ID) VALUES(1, 4);

INSERT INTO PATIO(NUMERO_PATIO, ANDAR_ID) VALUES(1, 1);
INSERT INTO PATIO(NUMERO_PATIO, ANDAR_ID) VALUES(2, 1);
INSERT INTO PATIO(NUMERO_PATIO, ANDAR_ID) VALUES(3, 1);
INSERT INTO PATIO(NUMERO_PATIO, ANDAR_ID) VALUES(1, 2);
INSERT INTO PATIO(NUMERO_PATIO, ANDAR_ID) VALUES(2, 2);

INSERT INTO BLOCO(LETRA_BLOCO, PATIO_ID) VALUES('A', 1);
INSERT INTO BLOCO(LETRA_BLOCO, PATIO_ID) VALUES('B', 1);
INSERT INTO BLOCO(LETRA_BLOCO, PATIO_ID) VALUES('C', 1);
INSERT INTO BLOCO(LETRA_BLOCO, PATIO_ID) VALUES('D', 1);
INSERT INTO BLOCO(LETRA_BLOCO, PATIO_ID) VALUES('E', 1);

INSERT INTO VAGA(NUMERO_VAGA, BLOCO_ID) VALUES(1, 1);
INSERT INTO VAGA(NUMERO_VAGA, BLOCO_ID) VALUES(2, 1);
INSERT INTO VAGA(NUMERO_VAGA, BLOCO_ID) VALUES(3, 1);
INSERT INTO VAGA(NUMERO_VAGA, BLOCO_ID) VALUES(4, 1);
INSERT INTO VAGA(NUMERO_VAGA, BLOCO_ID) VALUES(5, 1);

INSERT INTO MOTO (STATUS, MODELO, MARCA, PLACA, CHASSI, VAGA_ID) VALUES ('Disponivel', 'CG 160', 'Honda', 'ABC1234', '9C2KC0810FR123456', 1);
INSERT INTO MOTO (STATUS, MODELO, MARCA, PLACA, CHASSI, VAGA_ID) VALUES ('Em uso', 'Fazer 250', 'Yamaha', 'DEF5678', '9C2JC4110RR123456',2);
INSERT INTO MOTO (STATUS, MODELO, MARCA, PLACA, CHASSI, VAGA_ID) VALUES ('Manutencao', 'Ninja 400', 'Kawasaki', 'GHI9012', 'JKAEX8A1XKDA12345', 3);
INSERT INTO MOTO (STATUS, MODELO, MARCA, PLACA, CHASSI, VAGA_ID) VALUES ('Disponivel', 'MT-03', 'Yamaha', 'JKL3456', '9C6KE0810FR789012', 4);
INSERT INTO MOTO (STATUS, MODELO, MARCA, PLACA, CHASSI, VAGA_ID) VALUES ('Em uso', 'CB 500F', 'Honda', 'MNO7890', '9C2PC0810FR345678', 4);

INSERT INTO USUARIO (USERNAME, SENHA, NOME) VALUES ('jsilva', '$2a$10$cWmYOtcwKUpOu2xNwMdX.ODgeUNd4bCBrNeMLDJYdTlXWeOoO.AS2', 'João Silva');
INSERT INTO USUARIO (USERNAME, SENHA, NOME) VALUES ('ppereira', '$2a$10$cWmYOtcwKUpOu2xNwMdX.ODgeUNd4bCBrNeMLDJYdTlXWeOoO.AS2', 'Pedro Pereira');
INSERT INTO USUARIO (USERNAME, SENHA, NOME) VALUES ('msilva', '$2a$10$cWmYOtcwKUpOu2xNwMdX.ODgeUNd4bCBrNeMLDJYdTlXWeOoO.AS2', 'Matheus Silva');

INSERT INTO CARGO (NOME) VALUES ('ADMINISTRADOR');
INSERT INTO CARGO (NOME) VALUES ('OPERADOR');
INSERT INTO CARGO (NOME) VALUES ('SUPERVISOR');

INSERT INTO USUARIO_CARGO (USUARIO_ID, CARGO_ID) VALUES (1,1);
INSERT INTO USUARIO_CARGO (USUARIO_ID, CARGO_ID) VALUES (2,2);
INSERT INTO USUARIO_CARGO (USUARIO_ID, CARGO_ID) VALUES (3,3);